"""Adding more tools to c8bot"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_deeplearning_course.lesson6.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/01_deeplearning_course.lesson6.ipynb 2
import nbdev; nbdev.nbdev_export('01_deeplearning_course.lesson6.ipynb')
